### ISSUE TITLE
Editing file in Atom unfolds previously folded branches

### ISSUE THREAD

**Issue by avkonst** [dundalek/atom-markdown-mindmap#20]
This is another suggestion. I have got huge mindmap, like 1000x elements, 7 levels of nesting. At a time I explore / edit only subset of the map, trying to keep irrelevant branches closed for easy of navigation. However, when I add new items to the map, all branches are unfolded again, and it becomes not usable again. Folding all unnecessary branch again is even more inconvenient.

**Comment by dundalek** [comment]
I confirm this is an inconvenient behavior. Since the changes come through markdown text there is no straightforward way to map the changes to data structure changes. We would have to implement some kind of tree diffing. Hopefully I will come up with a simple enough solution, but I can't promise anything.

**Comment by dundalek** [comment]
This is now fixed in the latest version (`0.6.0`).
